-- Phase 2B supplier qualification and confidential sourcing vertical slice.
CREATE TYPE supplier_status AS ENUM ('DRAFT','PENDING_QUALIFICATION','ACTIVE','SUSPENDED','BLOCKED','INACTIVE','REJECTED');
CREATE TYPE qualification_status AS ENUM ('NOT_STARTED','PENDING','UNDER_REVIEW','APPROVED','REJECTED','EXPIRED');
CREATE TYPE rfq_status AS ENUM ('DRAFT','READY_FOR_REVIEW','PUBLISHED','CLARIFICATION_OPEN','QUOTATION_OPEN','QUOTATION_CLOSED','CANCELLED','CLOSED');
CREATE TYPE invitation_status AS ENUM ('DRAFT','SENT','VIEWED','ACCEPTED','DECLINED','EXPIRED','REVOKED');
CREATE TYPE quotation_status AS ENUM ('DRAFT','SUBMITTED','REVISED','WITHDRAWN','LATE_REJECTED','LOCKED');
CREATE TYPE clarification_visibility AS ENUM ('PRIVATE','PUBLIC');

CREATE TABLE suppliers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), supplier_number varchar(50) NOT NULL, legal_name varchar(250) NOT NULL, trading_name varchar(250), supplier_type varchar(50) NOT NULL, status supplier_status NOT NULL DEFAULT 'DRAFT', tax_registration_number varchar(100), commercial_registration_number varchar(100), country char(2) NOT NULL, default_currency char(3) NOT NULL, website varchar(500), primary_email varchar(320), primary_phone varchar(50), payment_terms varchar(500), preferred_language varchar(10) NOT NULL DEFAULT 'en', risk_classification varchar(50), qualification_status qualification_status NOT NULL DEFAULT 'NOT_STARTED', onboarding_status varchar(50) NOT NULL DEFAULT 'NOT_STARTED', suspended_at timestamptz, suspended_by uuid, suspension_reason varchar(1000), blocked_at timestamptz, blocked_by uuid, block_reason varchar(1000), version integer NOT NULL DEFAULT 1 CHECK(version>0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), UNIQUE(tenant_id,supplier_number));
CREATE TABLE supplier_contacts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, supplier_id uuid NOT NULL, full_name varchar(200) NOT NULL, job_title varchar(150), department varchar(150), email varchar(320), phone varchar(50), contact_type varchar(50) NOT NULL, is_primary boolean NOT NULL DEFAULT false, active boolean NOT NULL DEFAULT true, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), UNIQUE(tenant_id,supplier_id,id), FOREIGN KEY(tenant_id,supplier_id) REFERENCES suppliers(tenant_id,id));
CREATE TABLE supplier_addresses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, supplier_id uuid NOT NULL, address_type varchar(20) NOT NULL CHECK(address_type IN ('REGISTERED','BILLING','SHIPPING')), country char(2) NOT NULL, city varchar(120) NOT NULL, postal_code varchar(30), address_line_1 varchar(250) NOT NULL, address_line_2 varchar(250), active boolean NOT NULL DEFAULT true, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,supplier_id) REFERENCES suppliers(tenant_id,id));
CREATE TABLE supplier_categories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, code varchar(50) NOT NULL, name varchar(200) NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), UNIQUE(tenant_id,code));
CREATE TABLE supplier_category_assignments (tenant_id uuid NOT NULL, supplier_id uuid NOT NULL, category_id uuid NOT NULL, assigned_at timestamptz NOT NULL DEFAULT now(), assigned_by uuid NOT NULL, PRIMARY KEY(tenant_id,supplier_id,category_id), FOREIGN KEY(tenant_id,supplier_id) REFERENCES suppliers(tenant_id,id), FOREIGN KEY(tenant_id,category_id) REFERENCES supplier_categories(tenant_id,id));
CREATE TABLE supplier_qualification_records (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, supplier_id uuid NOT NULL, qualification_type varchar(100) NOT NULL, status qualification_status NOT NULL DEFAULT 'NOT_STARTED', reviewer_id uuid, submitted_at timestamptz, reviewed_at timestamptz, expiry_date date, decision_comment varchar(2000), internal_risk_notes varchar(4000), supporting_file_ids uuid[] NOT NULL DEFAULT '{}', version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,supplier_id) REFERENCES suppliers(tenant_id,id));
CREATE TABLE supplier_compliance_documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, supplier_id uuid NOT NULL, document_type varchar(100) NOT NULL, file_object_id uuid NOT NULL, document_number varchar(100), issue_date date, expiry_date date, verification_status varchar(30) NOT NULL DEFAULT 'PENDING', verified_by uuid, verified_at timestamptz, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,supplier_id) REFERENCES suppliers(tenant_id,id), FOREIGN KEY(tenant_id,file_object_id) REFERENCES file_objects(tenant_id,id));
CREATE TABLE supplier_internal_notes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, supplier_id uuid NOT NULL, author_id uuid NOT NULL, note varchar(4000) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,supplier_id) REFERENCES suppliers(tenant_id,id));
CREATE TABLE supplier_user_memberships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, supplier_id uuid NOT NULL, user_id uuid NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), revoked_at timestamptz, UNIQUE(tenant_id,id), UNIQUE(tenant_id,supplier_id,user_id), FOREIGN KEY(tenant_id,supplier_id) REFERENCES suppliers(tenant_id,id));

CREATE TABLE rfqs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), rfq_number varchar(50) NOT NULL, title varchar(250) NOT NULL, description varchar(4000), procurement_category varchar(150) NOT NULL, buyer_id uuid NOT NULL, currency char(3) NOT NULL, issue_date date, submission_deadline timestamptz NOT NULL, clarification_deadline timestamptz NOT NULL, required_by date NOT NULL, delivery_location varchar(500) NOT NULL, commercial_terms text, payment_terms varchar(1000), confidentiality_instructions varchar(2000), status rfq_status NOT NULL DEFAULT 'DRAFT', version integer NOT NULL DEFAULT 1, published_at timestamptz, closed_at timestamptz, cancelled_at timestamptz, cancellation_reason varchar(1000), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), UNIQUE(tenant_id,rfq_number), CHECK(clarification_deadline<=submission_deadline));
CREATE TABLE rfq_lines (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, rfq_id uuid NOT NULL, source_purchase_request_line_id uuid, description varchar(1000) NOT NULL, item_type purchase_item_type NOT NULL, quantity numeric(20,6) NOT NULL CHECK(quantity>0), unit_of_measure varchar(50) NOT NULL, specifications text NOT NULL, required_by date NOT NULL, delivery_location varchar(500) NOT NULL, category varchar(150) NOT NULL, target_currency char(3), line_sequence integer NOT NULL CHECK(line_sequence>0), source_snapshot jsonb NOT NULL DEFAULT '{}', version integer NOT NULL DEFAULT 1, UNIQUE(tenant_id,id), UNIQUE(tenant_id,rfq_id,id), UNIQUE(tenant_id,rfq_id,line_sequence), FOREIGN KEY(tenant_id,rfq_id) REFERENCES rfqs(tenant_id,id), FOREIGN KEY(tenant_id,source_purchase_request_line_id) REFERENCES purchase_request_items(tenant_id,id));
CREATE TABLE rfq_purchase_request_links (tenant_id uuid NOT NULL, rfq_id uuid NOT NULL, purchase_request_id uuid NOT NULL, source_snapshot jsonb NOT NULL, linked_at timestamptz NOT NULL DEFAULT now(), linked_by uuid NOT NULL, PRIMARY KEY(tenant_id,rfq_id,purchase_request_id), FOREIGN KEY(tenant_id,rfq_id) REFERENCES rfqs(tenant_id,id), FOREIGN KEY(tenant_id,purchase_request_id) REFERENCES purchase_requests(tenant_id,id));
CREATE TABLE rfq_supplier_invitations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, rfq_id uuid NOT NULL, supplier_id uuid NOT NULL, supplier_contact_id uuid, status invitation_status NOT NULL DEFAULT 'DRAFT', sent_at timestamptz, viewed_at timestamptz, accepted_at timestamptz, declined_at timestamptz, decline_reason varchar(1000), access_scope jsonb NOT NULL DEFAULT '{}', expires_at timestamptz NOT NULL, reminder_metadata jsonb NOT NULL DEFAULT '{}', version integer NOT NULL DEFAULT 1, UNIQUE(tenant_id,id), UNIQUE(tenant_id,rfq_id,supplier_id), FOREIGN KEY(tenant_id,rfq_id) REFERENCES rfqs(tenant_id,id), FOREIGN KEY(tenant_id,supplier_id) REFERENCES suppliers(tenant_id,id), FOREIGN KEY(tenant_id,supplier_id,supplier_contact_id) REFERENCES supplier_contacts(tenant_id,supplier_id,id));
CREATE TABLE rfq_clarification_threads (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, rfq_id uuid NOT NULL, requesting_supplier_id uuid, visibility clarification_visibility NOT NULL, status varchar(20) NOT NULL DEFAULT 'OPEN', subject varchar(250) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), closed_at timestamptz, UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,rfq_id) REFERENCES rfqs(tenant_id,id), FOREIGN KEY(tenant_id,requesting_supplier_id) REFERENCES suppliers(tenant_id,id));
CREATE TABLE rfq_clarification_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, thread_id uuid NOT NULL, author_id uuid NOT NULL, author_supplier_id uuid, visibility clarification_visibility NOT NULL DEFAULT 'PRIVATE', body varchar(8000) NOT NULL, attachment_file_ids uuid[] NOT NULL DEFAULT '{}', published_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,thread_id) REFERENCES rfq_clarification_threads(tenant_id,id), FOREIGN KEY(tenant_id,author_supplier_id) REFERENCES suppliers(tenant_id,id));
CREATE TABLE quotations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, quotation_number varchar(50) NOT NULL, rfq_id uuid NOT NULL, supplier_id uuid NOT NULL, currency char(3) NOT NULL, total_amount numeric(20,4) NOT NULL DEFAULT 0 CHECK(total_amount>=0), tax_amount numeric(20,4) NOT NULL DEFAULT 0 CHECK(tax_amount>=0), delivery_lead_time integer, validity_date date, payment_terms varchar(1000), incoterms varchar(20), commercial_comments text, technical_comments text, status quotation_status NOT NULL DEFAULT 'DRAFT', submitted_at timestamptz, withdrawn_at timestamptz, withdrawal_reason varchar(1000), current_revision integer NOT NULL DEFAULT 0, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), UNIQUE(tenant_id,rfq_id,id), UNIQUE(tenant_id,quotation_number), UNIQUE(tenant_id,rfq_id,supplier_id), FOREIGN KEY(tenant_id,rfq_id) REFERENCES rfqs(tenant_id,id), FOREIGN KEY(tenant_id,supplier_id) REFERENCES suppliers(tenant_id,id));
CREATE TABLE quotation_lines (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, quotation_id uuid NOT NULL, rfq_id uuid NOT NULL, rfq_line_id uuid NOT NULL, offered_description varchar(1000) NOT NULL, quantity numeric(20,6) NOT NULL CHECK(quantity>0), unit_price numeric(20,4) NOT NULL CHECK(unit_price>=0), discount numeric(20,4) NOT NULL DEFAULT 0 CHECK(discount>=0), tax numeric(20,4) NOT NULL DEFAULT 0 CHECK(tax>=0), net_line_amount numeric(20,4) GENERATED ALWAYS AS (round(quantity*unit_price-discount+tax,4)) STORED, delivery_date date, delivery_lead_time integer, compliance_response varchar(2000) NOT NULL, alternative_offer boolean NOT NULL DEFAULT false, supplier_comments varchar(2000), version integer NOT NULL DEFAULT 1, UNIQUE(tenant_id,id), UNIQUE(tenant_id,quotation_id,rfq_line_id), FOREIGN KEY(tenant_id,rfq_id,quotation_id) REFERENCES quotations(tenant_id,rfq_id,id), FOREIGN KEY(tenant_id,rfq_id,rfq_line_id) REFERENCES rfq_lines(tenant_id,rfq_id,id));
CREATE TABLE quotation_revisions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, quotation_id uuid NOT NULL, revision_number integer NOT NULL, snapshot jsonb NOT NULL, submitted_by uuid NOT NULL, submitted_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), UNIQUE(tenant_id,quotation_id,revision_number), FOREIGN KEY(tenant_id,quotation_id) REFERENCES quotations(tenant_id,id));
CREATE TABLE quotation_attachments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, quotation_id uuid NOT NULL, file_object_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,quotation_id) REFERENCES quotations(tenant_id,id), FOREIGN KEY(tenant_id,file_object_id) REFERENCES file_objects(tenant_id,id));
CREATE TABLE rfq_terms (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, rfq_id uuid NOT NULL, term_type varchar(50) NOT NULL, content text NOT NULL, sequence integer NOT NULL, version integer NOT NULL DEFAULT 1, UNIQUE(tenant_id,id), UNIQUE(tenant_id,rfq_id,sequence), FOREIGN KEY(tenant_id,rfq_id) REFERENCES rfqs(tenant_id,id));
CREATE TABLE rfq_activity_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, rfq_id uuid NOT NULL, actor_id uuid, supplier_id uuid, action varchar(100) NOT NULL, prior_state jsonb, resulting_state jsonb, correlation_id varchar(100) NOT NULL, redacted_metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,rfq_id) REFERENCES rfqs(tenant_id,id));

-- Every Phase 2B table is tenant-owned and fails closed without transaction-local tenant context.
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['suppliers','supplier_contacts','supplier_addresses','supplier_categories','supplier_category_assignments','supplier_qualification_records','supplier_compliance_documents','supplier_internal_notes','supplier_user_memberships','rfqs','rfq_lines','rfq_purchase_request_links','rfq_supplier_invitations','rfq_clarification_threads','rfq_clarification_messages','quotations','quotation_lines','quotation_revisions','quotation_attachments','rfq_terms','rfq_activity_events'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',t); EXECUTE format('CREATE POLICY tenant_isolation ON %I USING (tenant_id = NULLIF(current_setting(''app.current_tenant_id'', true), '''')::uuid) WITH CHECK (tenant_id = NULLIF(current_setting(''app.current_tenant_id'', true), '''')::uuid)',t); END LOOP; END $$;
-- Published sourcing communications and revision history are immutable.
CREATE FUNCTION prevent_phase_2b_immutable_change() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'immutable sourcing record'; END $$;
CREATE TRIGGER quotation_revisions_immutable BEFORE UPDATE OR DELETE ON quotation_revisions FOR EACH ROW EXECUTE FUNCTION prevent_phase_2b_immutable_change();
CREATE TRIGGER clarification_messages_immutable BEFORE UPDATE OR DELETE ON rfq_clarification_messages FOR EACH ROW EXECUTE FUNCTION prevent_phase_2b_immutable_change();
CREATE TRIGGER rfq_activity_immutable BEFORE UPDATE OR DELETE ON rfq_activity_events FOR EACH ROW EXECUTE FUNCTION prevent_phase_2b_immutable_change();
CREATE TABLE sourcing_idempotency (tenant_id uuid NOT NULL, actor_id uuid NOT NULL, operation varchar(100) NOT NULL, object_id uuid NOT NULL, idempotency_key varchar(128) NOT NULL, payload_hash char(64) NOT NULL, response jsonb, completed boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(tenant_id,actor_id,operation,object_id,idempotency_key));
ALTER TABLE sourcing_idempotency ENABLE ROW LEVEL SECURITY; ALTER TABLE sourcing_idempotency FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON sourcing_idempotency USING (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid) WITH CHECK (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid);
-- Supplier-facing defense in depth. Internal actors retain tenant policy access; supplier actors are bound to persisted supplier context.
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['quotations'] LOOP
  EXECUTE format('DROP POLICY tenant_isolation ON %I',t);
  EXECUTE format('CREATE POLICY tenant_and_supplier_isolation ON %I USING (tenant_id=NULLIF(current_setting(''app.current_tenant_id'',true),'''')::uuid AND (current_setting(''app.actor_type'',true)<>''supplier_user'' OR supplier_id=NULLIF(current_setting(''app.current_supplier_id'',true),'''')::uuid)) WITH CHECK (tenant_id=NULLIF(current_setting(''app.current_tenant_id'',true),'''')::uuid AND (current_setting(''app.actor_type'',true)<>''supplier_user'' OR supplier_id=NULLIF(current_setting(''app.current_supplier_id'',true),'''')::uuid))',t);
END LOOP; END $$;
DROP POLICY tenant_isolation ON rfq_supplier_invitations;
CREATE POLICY invitation_select ON rfq_supplier_invitations FOR SELECT USING (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid AND (current_setting('app.actor_type',true)<>'supplier_user' OR supplier_id=NULLIF(current_setting('app.current_supplier_id',true),'')::uuid));
CREATE POLICY invitation_insert_internal ON rfq_supplier_invitations FOR INSERT WITH CHECK (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid AND current_setting('app.actor_type',true)='internal_user');
CREATE POLICY invitation_update ON rfq_supplier_invitations FOR UPDATE USING (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid AND (current_setting('app.actor_type',true)<>'supplier_user' OR supplier_id=NULLIF(current_setting('app.current_supplier_id',true),'')::uuid)) WITH CHECK (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid AND (current_setting('app.actor_type',true)<>'supplier_user' OR supplier_id=NULLIF(current_setting('app.current_supplier_id',true),'')::uuid));
CREATE POLICY invitation_delete_internal ON rfq_supplier_invitations FOR DELETE USING (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid AND current_setting('app.actor_type',true)='internal_user');
DROP POLICY tenant_isolation ON quotation_lines;
CREATE POLICY tenant_and_supplier_isolation ON quotation_lines USING (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid AND (current_setting('app.actor_type',true)<>'supplier_user' OR EXISTS(SELECT 1 FROM quotations q WHERE q.id=quotation_id AND q.supplier_id=NULLIF(current_setting('app.current_supplier_id',true),'')::uuid))) WITH CHECK (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid AND (current_setting('app.actor_type',true)<>'supplier_user' OR EXISTS(SELECT 1 FROM quotations q WHERE q.id=quotation_id AND q.supplier_id=NULLIF(current_setting('app.current_supplier_id',true),'')::uuid)));
DROP POLICY tenant_isolation ON quotation_revisions;
CREATE POLICY tenant_and_supplier_isolation ON quotation_revisions USING (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid AND (current_setting('app.actor_type',true)<>'supplier_user' OR EXISTS(SELECT 1 FROM quotations q WHERE q.id=quotation_id AND q.supplier_id=NULLIF(current_setting('app.current_supplier_id',true),'')::uuid)));
DROP POLICY tenant_isolation ON quotation_attachments;
CREATE POLICY tenant_and_supplier_isolation ON quotation_attachments USING (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid AND (current_setting('app.actor_type',true)<>'supplier_user' OR EXISTS(SELECT 1 FROM quotations q WHERE q.id=quotation_id AND q.supplier_id=NULLIF(current_setting('app.current_supplier_id',true),'')::uuid)));
-- Supplier actors may see only files they uploaded or files attached to their own quotation; internal file workflows retain tenant access.
DROP POLICY tenant_isolation ON file_objects;
CREATE POLICY file_select_scope ON file_objects FOR SELECT USING (
  tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid
  AND (current_setting('app.actor_type',true) IS DISTINCT FROM 'supplier_user'
    OR uploader_id=NULLIF(current_setting('app.current_actor_id',true),'')::uuid
    OR EXISTS (SELECT 1 FROM quotation_attachments qa JOIN quotations q ON q.tenant_id=qa.tenant_id AND q.id=qa.quotation_id WHERE qa.tenant_id=file_objects.tenant_id AND qa.file_object_id=file_objects.id AND q.supplier_id=NULLIF(current_setting('app.current_supplier_id',true),'')::uuid))
);
CREATE POLICY file_insert_scope ON file_objects FOR INSERT WITH CHECK (
  tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid
  AND (current_setting('app.actor_type',true) IS DISTINCT FROM 'supplier_user' OR uploader_id=NULLIF(current_setting('app.current_actor_id',true),'')::uuid)
);
CREATE POLICY file_update_scope ON file_objects FOR UPDATE USING (
  tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid
  AND (current_setting('app.actor_type',true) IS DISTINCT FROM 'supplier_user' OR uploader_id=NULLIF(current_setting('app.current_actor_id',true),'')::uuid)
) WITH CHECK (
  tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid
  AND (current_setting('app.actor_type',true) IS DISTINCT FROM 'supplier_user' OR uploader_id=NULLIF(current_setting('app.current_actor_id',true),'')::uuid)
);
CREATE POLICY file_delete_scope ON file_objects FOR DELETE USING (
  tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid
  AND (current_setting('app.actor_type',true) IS DISTINCT FROM 'supplier_user' OR uploader_id=NULLIF(current_setting('app.current_actor_id',true),'')::uuid)
);

DROP POLICY tenant_isolation ON rfq_clarification_threads;
CREATE POLICY clarification_thread_scope ON rfq_clarification_threads FOR SELECT USING (
  tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid
  AND (current_setting('app.actor_type',true)<>'supplier_user'
    OR requesting_supplier_id=NULLIF(current_setting('app.current_supplier_id',true),'')::uuid
    OR (visibility='PUBLIC' AND EXISTS (
      SELECT 1 FROM rfq_supplier_invitations i
      WHERE i.tenant_id=rfq_clarification_threads.tenant_id AND i.rfq_id=rfq_clarification_threads.rfq_id
        AND i.supplier_id=NULLIF(current_setting('app.current_supplier_id',true),'')::uuid
        AND i.status IN ('SENT','VIEWED','ACCEPTED')
    ))
  )
);
CREATE POLICY clarification_thread_insert_scope ON rfq_clarification_threads FOR INSERT WITH CHECK (
  tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid
  AND (current_setting('app.actor_type',true)<>'supplier_user' OR (visibility='PRIVATE' AND requesting_supplier_id=NULLIF(current_setting('app.current_supplier_id',true),'')::uuid))
);
CREATE POLICY clarification_thread_update_internal ON rfq_clarification_threads FOR UPDATE USING (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid AND current_setting('app.actor_type',true)<>'supplier_user') WITH CHECK (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid AND current_setting('app.actor_type',true)<>'supplier_user');
DROP POLICY tenant_isolation ON rfq_clarification_messages;
CREATE POLICY clarification_message_scope ON rfq_clarification_messages FOR SELECT USING (
  tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid
  AND (current_setting('app.actor_type',true)<>'supplier_user'
    OR EXISTS (
      SELECT 1 FROM rfq_clarification_threads t
      WHERE t.tenant_id=rfq_clarification_messages.tenant_id AND t.id=thread_id
        AND (t.requesting_supplier_id=NULLIF(current_setting('app.current_supplier_id',true),'')::uuid
          OR (t.visibility='PUBLIC' AND rfq_clarification_messages.visibility='PUBLIC' AND rfq_clarification_messages.author_supplier_id IS NULL))
    )
  )
);
CREATE POLICY clarification_message_insert_scope ON rfq_clarification_messages FOR INSERT WITH CHECK (
  tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid
  AND (current_setting('app.actor_type',true)<>'supplier_user'
    OR (visibility='PRIVATE' AND author_supplier_id=NULLIF(current_setting('app.current_supplier_id',true),'')::uuid
      AND EXISTS (SELECT 1 FROM rfq_clarification_threads t WHERE t.tenant_id=rfq_clarification_messages.tenant_id AND t.id=thread_id AND t.requesting_supplier_id=author_supplier_id)))
);
