import 'reflect-metadata';
import helmet from 'helmet';
import { ValidationPipe, VersioningType } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { loadConfig } from '@procurement/config';
import { AppModule } from './app.module.js';
import { correlationIdMiddleware } from './common/correlation.js';
const config = loadConfig();
const app = await NestFactory.create(AppModule, { bufferLogs: true });
app.use(helmet());
app.use(correlationIdMiddleware);
app.enableCors({ origin: config.CORS_ORIGIN, credentials: true });
app.enableVersioning({ type: VersioningType.URI, defaultVersion: '1' });
app.useGlobalPipes(new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true, transform: true }));
const doc = SwaggerModule.createDocument(app, new DocumentBuilder().setTitle('Procurement Platform Foundation API').setVersion('1.0').build());
SwaggerModule.setup('docs', app, doc);
await app.listen(config.PORT);
